import type { fr } from "./fr";

export const en: typeof fr = {
  meta: {
    title: "Wided Rouatbi — Senior Product Designer",
    description:
      "I make complex business products legible, with AI in my process. Senior UX/UI Product Designer, 6+ years, B2B SaaS, tax, banking, travel.",
  },
  a11y: {
    skip: "Skip to content",
    pageChanged: "Page loaded:",
  },
  nav: {
    home: "Home",
    work: "Work",
    caseStudy: "Mathis BS case study",
    contact: "Contact",
    menu: "Menu",
    close: "Close",
    cta: "Get in touch",
    language: "Language",
    menuLabel: "Main navigation",
    localTime: "Local time",
  },
  cursor: {
    view: "View",
    drag: "Drag",
    next: "Next",
    open: "Open",
  },
  loader: {
    role: "Senior Product Designer",
  },
  hero: {
    eyebrow: "Wided Rouatbi — Senior Product Designer",
    title: "I make complex business products legible,",
    titleEm: "with AI in my process.",
    location: "Sousse, Tunisia → France",
    carouselLabel: "Featured projects",
    carouselRole: "carousel",
    slideOf: "Project {i} of {n}",
    prev: "Previous project",
    next: "Next project",
    scroll: "Scroll",
    hint: "Drag or use ← →",
  },
  intro: {
    label: "Approach",
    text: "I design complex business products and make them legible — from research to prototype, with AI as an accelerator.",
    cv: "Download my CV",
    portraitAlt: "Portrait of Wided Rouatbi",
  },
  figures: {
    label: "In numbers",
    items: [
      { value: 6, suffix: "+", label: "years of UX/UI experience" },
      { value: 20, suffix: "+", label: "projects shipped, from SaaS to mobile apps" },
      { value: 4, suffix: "", label: "sectors: B2B SaaS, fintech, e-commerce, travel" },
    ],
  },
  work: {
    label: "Selected work",
    title: "Dense products,",
    titleEm: "made simple.",
    viewAll: "See all projects",
  },
  marquee: {
    label: "Clients I've worked with",
    skills: ["UX Research", "Design Systems", "AI-Augmented Design", "Product Strategy", "Prototyping", "Design + Code"],
  },
  expertise: {
    label: "Expertise",
    title: "What I bring to a product team",
    items: [
      {
        title: "Complex business domains",
        text: "Real-estate tax, banking, travel: I learn the domain before I draw. I work with domain experts so the interface speaks its users' language.",
        example: "Mathis BS: social-housing taxation turned into screens a non-specialist asset manager can use with confidence.",
        image: "/images/projects/mathis-bs.jpg",
      },
      {
        title: "Design systems at scale",
        text: "I build and evolve consistent systems across several clients and surfaces. Shared components save time for designers and developers alike.",
        example: "Attunea: one design system shared by the web app (CRM) and the website.",
        image: "/images/projects/attunea.jpg",
      },
      {
        title: "AI-augmented design",
        text: "AI speeds up exploring directions, structuring research and going from spec to design. I keep ownership of the decisions and correct what it produces.",
        example: "Travel Shaper: a conversational experience where an assistant guides users from choosing a destination to booking.",
        image: "/images/projects/travel-shaper.jpg",
      },
      {
        title: "Design + code",
        text: "I speak developers' language and prototype in the browser. Fewer back-and-forths, cleaner handoffs, details that survive implementation.",
        example: "This portfolio: designed and built by me, in Next.js and GSAP.",
        image: "/images/projects/planet-tax-solution.jpg",
      },
      {
        title: "Mentoring & teaching",
        text: "I taught UX/UI at the Sousse School of Fine Arts and trained 20+ students at GoMyCode. I coach junior designers and interns day to day.",
        example: "Satoripop: mentoring interns and junior designers for four years.",
        image: "/images/projects/clever-harvest.jpg",
      },
    ],
  },
  next: {
    label: "What's next",
    title: "Explore the case studies",
    cta: "See the work",
  },
  footer: {
    cta: "Let's work together",
    lead: "A complex product that needs to feel simple? Write to me.",
    copy: "Copy",
    copied: "Copied ✓",
    copiedAnnounce: "Email address copied",
    available: "Available for France",
    backToTop: "Back to top",
    rights: "Designed and built by Wided Rouatbi.",
    cvFr: "CV FR",
    cvEn: "CV EN",
  },
  workPage: {
    label: "Archive",
    title: "All projects",
    intro:
      "SaaS products, B2B platforms, websites and mobile apps, at Neoshore, Satoripop, Diginov, WeAre Moon and as a freelancer.",
    columns: { index: "No.", name: "Project", sector: "Sector", role: "Employer", duration: "Duration" },
    caseStudy: "Case study",
    count: "{n} projects",
  },
  project: {
    brief: "At a glance",
    client: "Client",
    sector: "Sector",
    role: "My role",
    duration: "Duration",
    year: "Year",
    employer: "Employer",
    status: "Status",
    live: "See the product",
    scroll: "Scroll",
    context: "The business context",
    problems: "What was in the way",
    solutions: "What I designed",
    answers: "→ answers",
    personas: "Day to day",
    personasNote: "Target profiles, as scoped with the Product Owner.",
    process: "How I worked",
    aiMakingOf: "AI making-of",
    before: "AI iteration",
    after: "Final version",
    sliderLabel: "Compare the AI iteration with the final version",
    screens: "Key screens",
    zoom: "Enlarge screen",
    closeLightbox: "Close",
    prevScreen: "Previous screen",
    nextScreen: "Next screen",
    results: "Results & learnings",
    learnings: "What I take away",
    next: "Next project",
    backToWork: "Back to work",
    overview: "The project",
    toc: "Contents",
  },
};
