export const fr = {
  meta: {
    title: "Wided Rouatbi — Senior Product Designer",
    description:
      "Je rends lisibles les produits métier complexes, avec l'IA dans mon process. Senior Product Designer UX/UI, 6+ ans, SaaS B2B, fiscalité, banque, voyage.",
  },
  a11y: {
    skip: "Aller au contenu",
    pageChanged: "Page chargée :",
  },
  nav: {
    home: "Accueil",
    work: "Projets",
    caseStudy: "Étude de cas Mathis BS",
    contact: "Contact",
    menu: "Menu",
    close: "Fermer",
    cta: "Me contacter",
    language: "Langue",
    menuLabel: "Navigation principale",
    localTime: "Heure locale",
  },
  cursor: {
    view: "Voir",
    drag: "Glisser",
    next: "Suivant",
    open: "Ouvrir",
  },
  loader: {
    role: "Senior Product Designer",
  },
  hero: {
    eyebrow: "Wided Rouatbi — Senior Product Designer",
    title: "Je rends lisibles les produits métier complexes,",
    titleEm: "avec l'IA dans mon process.",
    location: "Sousse, Tunisie → France",
    carouselLabel: "Projets phares",
    carouselRole: "carrousel",
    slideOf: "Projet {i} sur {n}",
    prev: "Projet précédent",
    next: "Projet suivant",
    scroll: "Défiler",
    hint: "Glissez ou utilisez ← →",
  },
  intro: {
    label: "Approche",
    text: "Je conçois des produits métier complexes et je les rends lisibles — de la recherche au prototype, avec l'IA comme accélérateur.",
    cv: "Télécharger mon CV",
    portraitAlt: "Portrait de Wided Rouatbi",
  },
  figures: {
    label: "En chiffres",
    items: [
      { value: 6, suffix: "+", label: "ans d'expérience en UX/UI" },
      { value: 20, suffix: "+", label: "projets livrés, du SaaS à l'app mobile" },
      { value: 4, suffix: "", label: "secteurs : SaaS B2B, fintech, e-commerce, voyage" },
    ],
  },
  work: {
    label: "Projets sélectionnés",
    title: "Des produits denses,",
    titleEm: "rendus simples.",
    viewAll: "Voir tous les projets",
  },
  marquee: {
    label: "Ils m'ont fait confiance",
    skills: ["UX Research", "Design Systems", "AI-Augmented Design", "Product Strategy", "Prototypage", "Design + Code"],
  },
  expertise: {
    label: "Expertise",
    title: "Ce que j'apporte à une équipe produit",
    items: [
      {
        title: "Domaines métier complexes",
        text: "Fiscalité immobilière, banque, voyage : j'apprends le métier avant de dessiner. Je travaille avec les experts du domaine pour que l'interface parle la langue de ses utilisateurs.",
        example: "Mathis BS : la fiscalité des bailleurs sociaux traduite en écrans qu'un gestionnaire non-fiscaliste utilise en confiance.",
        image: "/images/projects/mathis-bs.jpg",
      },
      {
        title: "Design systems à l'échelle",
        text: "Je construis et fais évoluer des systèmes cohérents sur plusieurs clients et plusieurs surfaces. Les composants partagés font gagner du temps aux designers comme aux développeurs.",
        example: "Attunea : un design system commun à l'app web (CRM) et au site.",
        image: "/images/projects/attunea.jpg",
      },
      {
        title: "Design augmenté par l'IA",
        text: "L'IA accélère l'exploration de pistes, la structuration de la recherche et le passage de la spec au design. Je garde la main sur les décisions et je corrige ce qu'elle produit.",
        example: "Travel Shaper : une expérience conversationnelle où un assistant guide du choix de destination à la réservation.",
        image: "/images/projects/travel-shaper.jpg",
      },
      {
        title: "Design + code",
        text: "Je parle le langage des développeurs et je prototype dans le navigateur. Moins d'allers-retours, des handoffs plus nets, des détails qui survivent à l'implémentation.",
        example: "Ce portfolio : conçu et développé par moi, en Next.js et GSAP.",
        image: "/images/projects/planet-tax-solution.jpg",
      },
      {
        title: "Mentorat & enseignement",
        text: "J'ai enseigné l'UX/UI aux Beaux-Arts de Sousse et formé plus de 20 étudiants chez GoMyCode. J'accompagne les designers juniors et les stagiaires au quotidien.",
        example: "Satoripop : mentorat de stagiaires et de designers juniors pendant quatre ans.",
        image: "/images/projects/clever-harvest.jpg",
      },
    ],
  },
  next: {
    label: "La suite",
    title: "Explorer les études de cas",
    cta: "Voir les projets",
  },
  footer: {
    cta: "Travaillons ensemble",
    lead: "Un produit complexe à rendre simple ? Écrivez-moi.",
    copy: "Copier",
    copied: "Copié ✓",
    copiedAnnounce: "Adresse email copiée",
    available: "Disponible pour la France",
    backToTop: "Retour en haut",
    rights: "Conçu et développé par Wided Rouatbi.",
    cvFr: "CV FR",
    cvEn: "CV EN",
  },
  workPage: {
    label: "Archive",
    title: "Tous les projets",
    intro:
      "Produits SaaS, plateformes B2B, sites web et apps mobiles, chez Neoshore, Satoripop, Diginov, WeAre Moon et en freelance.",
    columns: { index: "N°", name: "Projet", sector: "Secteur", role: "Employeur", duration: "Durée" },
    caseStudy: "Étude de cas",
    count: "{n} projets",
  },
  project: {
    brief: "En bref",
    client: "Client",
    sector: "Secteur",
    role: "Mon rôle",
    duration: "Durée",
    year: "Année",
    employer: "Employeur",
    status: "Statut",
    live: "Voir le produit",
    scroll: "Défiler",
    context: "Le contexte métier",
    problems: "Ce qui bloquait",
    solutions: "Ce que j'ai conçu",
    answers: "→ répond à",
    personas: "Au quotidien",
    personasNote: "Profils cibles, tels que cadrés avec le Product Owner.",
    process: "Comment j'ai travaillé",
    aiMakingOf: "Making-of IA",
    before: "Itération IA",
    after: "Version finale",
    sliderLabel: "Comparer l'itération IA et la version finale",
    screens: "Écrans clés",
    zoom: "Agrandir l'écran",
    closeLightbox: "Fermer",
    prevScreen: "Écran précédent",
    nextScreen: "Écran suivant",
    results: "Résultats & apprentissages",
    learnings: "Ce que j'en retiens",
    next: "Projet suivant",
    backToWork: "Retour aux projets",
    overview: "Le projet",
    toc: "Sommaire",
  },
};
